format:
  html: default
  pdf:
    documentclass: report
    papersize: a4
    geometry:
      - top = 30mm
      - left = 20mm
    number-sections: true
    keep-tex: false
    output-file: response_to_reviewers
    include-in-header: header.tex  
    header-includes:
     - \usepackage{xcolor}
bibliography:
  - references.bib

execute:
  echo: false
  warning: false
  message: false